# Imagem base - Usando Node.js 22 em versão leve (Alpine Linux)
FROM node:22-alpine

# Definindo diretório de trabalho dentro do container
WORKDIR /app

# Expõe a porta em que a aplicação vai rodar
EXPOSE 3000

# Instalar dependências e iniciar o servidor
CMD npm install && node server.js