services:
  app:
    # build na raiz do projeto
    build: frontend/
    container_name: app_info_suplementos
    ports:
      - "1531:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=info_suplementos
    volumes:
      # Montando toda a raiz no container
      - ./frontend:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: info_suplementos
    ports:
      - "1530:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: peneirada-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=admin
      - PMA_PASSWORD=info_suplementos
      - PMA_ARBITRARY=1
    ports:
      - "1522:80"
    depends_on:
      - db
    networks:
      - default
      
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
