services:
  mysql:
    image: mysql:8.0
    container_name: Infosuplementos_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: info123
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
